### ISSUE TITLE
Illegal scope error triggered by user-top-read

### ISSUE THREAD

**Issue by nicofilliol** [dtcrout/spotitude#13] opened 2019-06-12 15:35 UTC
`user-top-read` as a setting for the scope in the config file sometimes results in a `Illegal scope` error. (Check #3 for more details on the error.)

This might be a bug on Spotify's side (see [Issue #1262](https://github.com/spotify/web-api/issues/1262))

**WORKAROUND**
There seems to be a workaround for this by doing the following:

1. Go to https://developer.spotify.com/dashboard/applications
2. Create a new app
3. Set Redirect URI according to README instructions (or choose your own Redirect URI but make sure it is exactly the same everywhere)
4. Update credentials in spotitude.config file
5. Try again by running `python3 spotitude.py`
6. Repeat whole process (creating new app, start from point 1) until it works.

**Comment by mklaunzer** [comment] 2019-07-14 14:19
Thanks for your hint! This has been caused by a configuration issue on some our hosts and caused some newly created client ids missing the user-top-read scope. This has been fixed now - when creating a new client id, the scope should now always be available.
We are working on also adding it to the client ids which did not receive it during creation. This will take some more time, so if you need this to work urgently, please create a new client id for now.

**Comment by dtcrout** [comment] 2019-07-14 16:00
Issue fixed: https://github.com/spotify/web-api/issues/1262#issuecomment-511206677

**Closed as completed by dtcrout** 2019-07-14 16:00 UTC
